[package]
name = "config-docs-macros"
version = "0.1.0"
edition = "2021"
description = "The derive macro for config-docs"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0.93"
